name: bsaseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mutmap = 2.3.3
  - fastp = 0.19.5
  - multiqc = 1.11
  - pyyaml = 6.0
  - snpeff = 5.0
  - samtools = 1.15.1
  - bwa = 0.7.15
