---
# directories
result_dir:  results/ # should be kept
working_dir: temp/    # can be removed (temporary files)
fastq_dir: config/fastq/ # location of fastq files

# samples to condition
samples: config/samples.csv

# refs 
ref_genome:  "config/refs/mutmap_ref.fasta" 

# threads
threads: 5

##############################
# fastp: read quality trimming
#############################

fastp:
  qualified_quality_phred: 30 # Phred+33 score (> 15 for Proton Ion, > 30 or more for Illumina) 


########
# MutMap
########

mutmap:
  window_size: '2000'               # window size in kb (default is 2000) [2000]
  step_size:   '100'                # step size in kb (default 100) [100]   
  max_depth:   '250'                # Maximum depth of variants which will be used. This cutoff will be applied in both of cultivar and bulk. [250]
  min_depth:   '8'                  # Minimum depth of variants which will be used. This cutoff will be applied in both of cultivar and bulk. [8]
  n_rep:       '5000'               # number of replicates for simulation to make the null distribution [5000]
  min_mq:      '40'                 # minimum mapping quality in mpileup. [40]
  min_bq:      '18'                 # minimum base quality in mpileup. [18]
  adjust_mq:   '50'                 # "adjust-MQ" in mpileup. Default parameter is suited for BWA. [50]
  n_ind:       '20'                 # number of individuals in the mutant bulk (n_ind = 20 for the test files: https://zenodo.org/record/5710370

###########
# snpEff
##########

snpeff:
  database_url: https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Arabidopsis_thaliana.zip # only for data provenance
  database: "Arabidopsis_thaliana" # corresponds to the database above >> check in /miniconda3/envs/bsaseq/share/snpeff-5.0-1/snpEff.config
  output_format: "vcf"
