---
# directories
result_dir:  results/       #  should be kept
working_dir: temp/          # can be removed (temporary files)
fastq_dir:   config/fastq/  # location of fastq files

# samples to condition
samples: config/samples.csv

# refs 
ref_genome:  "config/refs/IRGSP-1.0_genome.chr09.fasta" 

##############################
# fastp: read quality trimming
#############################

fastp:
  qualified_quality_phred: 30 # Phred+33 score (> 15 for Proton Ion, > 30 or more for Illumina) 


